//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeiboAnalysis.IDOLBLL {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryParamEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class QueryParamEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string actionField;
        
        private int StartField;
        
        private int PageSizeField;
        
        private int DisplayStyleField;
        
        private bool TotalResultsField;
        
        private int CharactersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HighlightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrintField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrintFieldsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SummaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PredictField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CombineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataBaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MinScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MinDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaxDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateMatchIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatchReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldNameField;
        
        private bool DocumentCountField;
        
        private int DisNumField;
        
        private bool DisOtherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatePeriodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string action {
            get {
                return this.actionField;
            }
            set {
                if ((object.ReferenceEquals(this.actionField, value) != true)) {
                    this.actionField = value;
                    this.RaisePropertyChanged("action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int DisplayStyle {
            get {
                return this.DisplayStyleField;
            }
            set {
                if ((this.DisplayStyleField.Equals(value) != true)) {
                    this.DisplayStyleField = value;
                    this.RaisePropertyChanged("DisplayStyle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool TotalResults {
            get {
                return this.TotalResultsField;
            }
            set {
                if ((this.TotalResultsField.Equals(value) != true)) {
                    this.TotalResultsField = value;
                    this.RaisePropertyChanged("TotalResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Characters {
            get {
                return this.CharactersField;
            }
            set {
                if ((this.CharactersField.Equals(value) != true)) {
                    this.CharactersField = value;
                    this.RaisePropertyChanged("Characters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Highlight {
            get {
                return this.HighlightField;
            }
            set {
                if ((object.ReferenceEquals(this.HighlightField, value) != true)) {
                    this.HighlightField = value;
                    this.RaisePropertyChanged("Highlight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Print {
            get {
                return this.PrintField;
            }
            set {
                if ((object.ReferenceEquals(this.PrintField, value) != true)) {
                    this.PrintField = value;
                    this.RaisePropertyChanged("Print");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string PrintFields {
            get {
                return this.PrintFieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.PrintFieldsField, value) != true)) {
                    this.PrintFieldsField = value;
                    this.RaisePropertyChanged("PrintFields");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Summary {
            get {
                return this.SummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SummaryField, value) != true)) {
                    this.SummaryField = value;
                    this.RaisePropertyChanged("Summary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Predict {
            get {
                return this.PredictField;
            }
            set {
                if ((object.ReferenceEquals(this.PredictField, value) != true)) {
                    this.PredictField = value;
                    this.RaisePropertyChanged("Predict");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Combine {
            get {
                return this.CombineField;
            }
            set {
                if ((object.ReferenceEquals(this.CombineField, value) != true)) {
                    this.CombineField = value;
                    this.RaisePropertyChanged("Combine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string DataBase {
            get {
                return this.DataBaseField;
            }
            set {
                if ((object.ReferenceEquals(this.DataBaseField, value) != true)) {
                    this.DataBaseField = value;
                    this.RaisePropertyChanged("DataBase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string MinScore {
            get {
                return this.MinScoreField;
            }
            set {
                if ((object.ReferenceEquals(this.MinScoreField, value) != true)) {
                    this.MinScoreField = value;
                    this.RaisePropertyChanged("MinScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string MinDate {
            get {
                return this.MinDateField;
            }
            set {
                if ((object.ReferenceEquals(this.MinDateField, value) != true)) {
                    this.MinDateField = value;
                    this.RaisePropertyChanged("MinDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string MaxDate {
            get {
                return this.MaxDateField;
            }
            set {
                if ((object.ReferenceEquals(this.MaxDateField, value) != true)) {
                    this.MaxDateField = value;
                    this.RaisePropertyChanged("MaxDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string FieldText {
            get {
                return this.FieldTextField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldTextField, value) != true)) {
                    this.FieldTextField = value;
                    this.RaisePropertyChanged("FieldText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string Sort {
            get {
                return this.SortField;
            }
            set {
                if ((object.ReferenceEquals(this.SortField, value) != true)) {
                    this.SortField = value;
                    this.RaisePropertyChanged("Sort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string StateMatchID {
            get {
                return this.StateMatchIDField;
            }
            set {
                if ((object.ReferenceEquals(this.StateMatchIDField, value) != true)) {
                    this.StateMatchIDField = value;
                    this.RaisePropertyChanged("StateMatchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string Reference {
            get {
                return this.ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceField, value) != true)) {
                    this.ReferenceField = value;
                    this.RaisePropertyChanged("Reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string MatchReference {
            get {
                return this.MatchReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchReferenceField, value) != true)) {
                    this.MatchReferenceField = value;
                    this.RaisePropertyChanged("MatchReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string QueryText {
            get {
                return this.QueryTextField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryTextField, value) != true)) {
                    this.QueryTextField = value;
                    this.RaisePropertyChanged("QueryText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string AgentName {
            get {
                return this.AgentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentNameField, value) != true)) {
                    this.AgentNameField = value;
                    this.RaisePropertyChanged("AgentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string FieldName {
            get {
                return this.FieldNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldNameField, value) != true)) {
                    this.FieldNameField = value;
                    this.RaisePropertyChanged("FieldName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=27)]
        public bool DocumentCount {
            get {
                return this.DocumentCountField;
            }
            set {
                if ((this.DocumentCountField.Equals(value) != true)) {
                    this.DocumentCountField = value;
                    this.RaisePropertyChanged("DocumentCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=28)]
        public int DisNum {
            get {
                return this.DisNumField;
            }
            set {
                if ((this.DisNumField.Equals(value) != true)) {
                    this.DisNumField = value;
                    this.RaisePropertyChanged("DisNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=29)]
        public bool DisOther {
            get {
                return this.DisOtherField;
            }
            set {
                if ((this.DisOtherField.Equals(value) != true)) {
                    this.DisOtherField = value;
                    this.RaisePropertyChanged("DisOther");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string DatePeriod {
            get {
                return this.DatePeriodField;
            }
            set {
                if ((object.ReferenceEquals(this.DatePeriodField, value) != true)) {
                    this.DatePeriodField = value;
                    this.RaisePropertyChanged("DatePeriod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDOLBLL.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 qpe 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTopicIDs", ReplyAction="*")]
        WeiboAnalysis.IDOLBLL.GetTopicIDsResponse GetTopicIDs(WeiboAnalysis.IDOLBLL.GetTopicIDsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 qpe 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIdolCount", ReplyAction="*")]
        WeiboAnalysis.IDOLBLL.GetIdolCountResponse GetIdolCount(WeiboAnalysis.IDOLBLL.GetIdolCountRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 que 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJsonData", ReplyAction="*")]
        WeiboAnalysis.IDOLBLL.GetJsonDataResponse GetJsonData(WeiboAnalysis.IDOLBLL.GetJsonDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTopicIDsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTopicIDs", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.IDOLBLL.GetTopicIDsRequestBody Body;
        
        public GetTopicIDsRequest() {
        }
        
        public GetTopicIDsRequest(WeiboAnalysis.IDOLBLL.GetTopicIDsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTopicIDsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WeiboAnalysis.IDOLBLL.QueryParamEntity qpe;
        
        public GetTopicIDsRequestBody() {
        }
        
        public GetTopicIDsRequestBody(WeiboAnalysis.IDOLBLL.QueryParamEntity qpe) {
            this.qpe = qpe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTopicIDsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTopicIDsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.IDOLBLL.GetTopicIDsResponseBody Body;
        
        public GetTopicIDsResponse() {
        }
        
        public GetTopicIDsResponse(WeiboAnalysis.IDOLBLL.GetTopicIDsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTopicIDsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTopicIDsResult;
        
        public GetTopicIDsResponseBody() {
        }
        
        public GetTopicIDsResponseBody(string GetTopicIDsResult) {
            this.GetTopicIDsResult = GetTopicIDsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIdolCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIdolCount", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.IDOLBLL.GetIdolCountRequestBody Body;
        
        public GetIdolCountRequest() {
        }
        
        public GetIdolCountRequest(WeiboAnalysis.IDOLBLL.GetIdolCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIdolCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WeiboAnalysis.IDOLBLL.QueryParamEntity qpe;
        
        public GetIdolCountRequestBody() {
        }
        
        public GetIdolCountRequestBody(WeiboAnalysis.IDOLBLL.QueryParamEntity qpe) {
            this.qpe = qpe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIdolCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIdolCountResponse", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.IDOLBLL.GetIdolCountResponseBody Body;
        
        public GetIdolCountResponse() {
        }
        
        public GetIdolCountResponse(WeiboAnalysis.IDOLBLL.GetIdolCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIdolCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetIdolCountResult;
        
        public GetIdolCountResponseBody() {
        }
        
        public GetIdolCountResponseBody(int GetIdolCountResult) {
            this.GetIdolCountResult = GetIdolCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetJsonDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetJsonData", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.IDOLBLL.GetJsonDataRequestBody Body;
        
        public GetJsonDataRequest() {
        }
        
        public GetJsonDataRequest(WeiboAnalysis.IDOLBLL.GetJsonDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetJsonDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WeiboAnalysis.IDOLBLL.QueryParamEntity que;
        
        public GetJsonDataRequestBody() {
        }
        
        public GetJsonDataRequestBody(WeiboAnalysis.IDOLBLL.QueryParamEntity que) {
            this.que = que;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetJsonDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetJsonDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.IDOLBLL.GetJsonDataResponseBody Body;
        
        public GetJsonDataResponse() {
        }
        
        public GetJsonDataResponse(WeiboAnalysis.IDOLBLL.GetJsonDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetJsonDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetJsonDataResult;
        
        public GetJsonDataResponseBody() {
        }
        
        public GetJsonDataResponseBody(string GetJsonDataResult) {
            this.GetJsonDataResult = GetJsonDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : WeiboAnalysis.IDOLBLL.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<WeiboAnalysis.IDOLBLL.Service1Soap>, WeiboAnalysis.IDOLBLL.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeiboAnalysis.IDOLBLL.GetTopicIDsResponse WeiboAnalysis.IDOLBLL.Service1Soap.GetTopicIDs(WeiboAnalysis.IDOLBLL.GetTopicIDsRequest request) {
            return base.Channel.GetTopicIDs(request);
        }
        
        public string GetTopicIDs(WeiboAnalysis.IDOLBLL.QueryParamEntity qpe) {
            WeiboAnalysis.IDOLBLL.GetTopicIDsRequest inValue = new WeiboAnalysis.IDOLBLL.GetTopicIDsRequest();
            inValue.Body = new WeiboAnalysis.IDOLBLL.GetTopicIDsRequestBody();
            inValue.Body.qpe = qpe;
            WeiboAnalysis.IDOLBLL.GetTopicIDsResponse retVal = ((WeiboAnalysis.IDOLBLL.Service1Soap)(this)).GetTopicIDs(inValue);
            return retVal.Body.GetTopicIDsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeiboAnalysis.IDOLBLL.GetIdolCountResponse WeiboAnalysis.IDOLBLL.Service1Soap.GetIdolCount(WeiboAnalysis.IDOLBLL.GetIdolCountRequest request) {
            return base.Channel.GetIdolCount(request);
        }
        
        public int GetIdolCount(WeiboAnalysis.IDOLBLL.QueryParamEntity qpe) {
            WeiboAnalysis.IDOLBLL.GetIdolCountRequest inValue = new WeiboAnalysis.IDOLBLL.GetIdolCountRequest();
            inValue.Body = new WeiboAnalysis.IDOLBLL.GetIdolCountRequestBody();
            inValue.Body.qpe = qpe;
            WeiboAnalysis.IDOLBLL.GetIdolCountResponse retVal = ((WeiboAnalysis.IDOLBLL.Service1Soap)(this)).GetIdolCount(inValue);
            return retVal.Body.GetIdolCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeiboAnalysis.IDOLBLL.GetJsonDataResponse WeiboAnalysis.IDOLBLL.Service1Soap.GetJsonData(WeiboAnalysis.IDOLBLL.GetJsonDataRequest request) {
            return base.Channel.GetJsonData(request);
        }
        
        public string GetJsonData(WeiboAnalysis.IDOLBLL.QueryParamEntity que) {
            WeiboAnalysis.IDOLBLL.GetJsonDataRequest inValue = new WeiboAnalysis.IDOLBLL.GetJsonDataRequest();
            inValue.Body = new WeiboAnalysis.IDOLBLL.GetJsonDataRequestBody();
            inValue.Body.que = que;
            WeiboAnalysis.IDOLBLL.GetJsonDataResponse retVal = ((WeiboAnalysis.IDOLBLL.Service1Soap)(this)).GetJsonData(inValue);
            return retVal.Body.GetJsonDataResult;
        }
    }
}
