//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34014 版自动生成。
// 
#pragma warning disable 1591

namespace WeiboAnalysis.WeiboDataSource {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WeiboDataServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WeiboDataService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTopicPagerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserPagerOperationCompleted;
        
        private System.Threading.SendOrPostCallback TopicUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHotTopicOperationCompleted;
        
        private System.Threading.SendOrPostCallback InitCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback CategoryUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback DelCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback InitKeywordsListOperationCompleted;
        
        private System.Threading.SendOrPostCallback DelKeywordsOperationCompleted;
        
        private System.Threading.SendOrPostCallback KeywordsUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserGroupListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GroupToAttentionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GroupAttentionUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddGroupAttentionOperationCompleted;
        
        private System.Threading.SendOrPostCallback DelAttentionGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback StatisticTopicOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WeiboDataService() {
            this.Url = global::WeiboAnalysis.Properties.Settings.Default.WeiboAnalysis_WeiboDataSource_WeiboDataService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTopicPagerCompletedEventHandler GetTopicPagerCompleted;
        
        /// <remarks/>
        public event GetUserPagerCompletedEventHandler GetUserPagerCompleted;
        
        /// <remarks/>
        public event TopicUpdateCompletedEventHandler TopicUpdateCompleted;
        
        /// <remarks/>
        public event GetHotTopicCompletedEventHandler GetHotTopicCompleted;
        
        /// <remarks/>
        public event InitCategoryCompletedEventHandler InitCategoryCompleted;
        
        /// <remarks/>
        public event CategoryUpdateCompletedEventHandler CategoryUpdateCompleted;
        
        /// <remarks/>
        public event DelCategoryCompletedEventHandler DelCategoryCompleted;
        
        /// <remarks/>
        public event InitKeywordsListCompletedEventHandler InitKeywordsListCompleted;
        
        /// <remarks/>
        public event DelKeywordsCompletedEventHandler DelKeywordsCompleted;
        
        /// <remarks/>
        public event KeywordsUpdateCompletedEventHandler KeywordsUpdateCompleted;
        
        /// <remarks/>
        public event GetUserGroupListCompletedEventHandler GetUserGroupListCompleted;
        
        /// <remarks/>
        public event GroupToAttentionCompletedEventHandler GroupToAttentionCompleted;
        
        /// <remarks/>
        public event GroupAttentionUpdateCompletedEventHandler GroupAttentionUpdateCompleted;
        
        /// <remarks/>
        public event AddGroupAttentionCompletedEventHandler AddGroupAttentionCompleted;
        
        /// <remarks/>
        public event DelAttentionGroupCompletedEventHandler DelAttentionGroupCompleted;
        
        /// <remarks/>
        public event StatisticTopicCompletedEventHandler StatisticTopicCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTopicPager", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTopicPager(string keywords, string topicindustry, string stime, string etime, int start, int pagesize) {
            object[] results = this.Invoke("GetTopicPager", new object[] {
                        keywords,
                        topicindustry,
                        stime,
                        etime,
                        start,
                        pagesize});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTopicPagerAsync(string keywords, string topicindustry, string stime, string etime, int start, int pagesize) {
            this.GetTopicPagerAsync(keywords, topicindustry, stime, etime, start, pagesize, null);
        }
        
        /// <remarks/>
        public void GetTopicPagerAsync(string keywords, string topicindustry, string stime, string etime, int start, int pagesize, object userState) {
            if ((this.GetTopicPagerOperationCompleted == null)) {
                this.GetTopicPagerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTopicPagerOperationCompleted);
            }
            this.InvokeAsync("GetTopicPager", new object[] {
                        keywords,
                        topicindustry,
                        stime,
                        etime,
                        start,
                        pagesize}, this.GetTopicPagerOperationCompleted, userState);
        }
        
        private void OnGetTopicPagerOperationCompleted(object arg) {
            if ((this.GetTopicPagerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTopicPagerCompleted(this, new GetTopicPagerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserPager", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserPager(string groupId, string mainuid, string websource, string attentionType, int start, int pagesize) {
            object[] results = this.Invoke("GetUserPager", new object[] {
                        groupId,
                        mainuid,
                        websource,
                        attentionType,
                        start,
                        pagesize});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserPagerAsync(string groupId, string mainuid, string websource, string attentionType, int start, int pagesize) {
            this.GetUserPagerAsync(groupId, mainuid, websource, attentionType, start, pagesize, null);
        }
        
        /// <remarks/>
        public void GetUserPagerAsync(string groupId, string mainuid, string websource, string attentionType, int start, int pagesize, object userState) {
            if ((this.GetUserPagerOperationCompleted == null)) {
                this.GetUserPagerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserPagerOperationCompleted);
            }
            this.InvokeAsync("GetUserPager", new object[] {
                        groupId,
                        mainuid,
                        websource,
                        attentionType,
                        start,
                        pagesize}, this.GetUserPagerOperationCompleted, userState);
        }
        
        private void OnGetUserPagerOperationCompleted(object arg) {
            if ((this.GetUserPagerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserPagerCompleted(this, new GetUserPagerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TopicUpdate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool TopicUpdate(string tname, string keyword, string industry, string sid, string stype) {
            object[] results = this.Invoke("TopicUpdate", new object[] {
                        tname,
                        keyword,
                        industry,
                        sid,
                        stype});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void TopicUpdateAsync(string tname, string keyword, string industry, string sid, string stype) {
            this.TopicUpdateAsync(tname, keyword, industry, sid, stype, null);
        }
        
        /// <remarks/>
        public void TopicUpdateAsync(string tname, string keyword, string industry, string sid, string stype, object userState) {
            if ((this.TopicUpdateOperationCompleted == null)) {
                this.TopicUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTopicUpdateOperationCompleted);
            }
            this.InvokeAsync("TopicUpdate", new object[] {
                        tname,
                        keyword,
                        industry,
                        sid,
                        stype}, this.TopicUpdateOperationCompleted, userState);
        }
        
        private void OnTopicUpdateOperationCompleted(object arg) {
            if ((this.TopicUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TopicUpdateCompleted(this, new TopicUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHotTopic", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetHotTopic(string topicType) {
            object[] results = this.Invoke("GetHotTopic", new object[] {
                        topicType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetHotTopicAsync(string topicType) {
            this.GetHotTopicAsync(topicType, null);
        }
        
        /// <remarks/>
        public void GetHotTopicAsync(string topicType, object userState) {
            if ((this.GetHotTopicOperationCompleted == null)) {
                this.GetHotTopicOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHotTopicOperationCompleted);
            }
            this.InvokeAsync("GetHotTopic", new object[] {
                        topicType}, this.GetHotTopicOperationCompleted, userState);
        }
        
        private void OnGetHotTopicOperationCompleted(object arg) {
            if ((this.GetHotTopicCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHotTopicCompleted(this, new GetHotTopicCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InitCategory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InitCategory() {
            object[] results = this.Invoke("InitCategory", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InitCategoryAsync() {
            this.InitCategoryAsync(null);
        }
        
        /// <remarks/>
        public void InitCategoryAsync(object userState) {
            if ((this.InitCategoryOperationCompleted == null)) {
                this.InitCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitCategoryOperationCompleted);
            }
            this.InvokeAsync("InitCategory", new object[0], this.InitCategoryOperationCompleted, userState);
        }
        
        private void OnInitCategoryOperationCompleted(object arg) {
            if ((this.InitCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InitCategoryCompleted(this, new InitCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CategoryUpdate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CategoryUpdate(string stype, string cateName, string catekeyword, string sid, string minscore) {
            object[] results = this.Invoke("CategoryUpdate", new object[] {
                        stype,
                        cateName,
                        catekeyword,
                        sid,
                        minscore});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CategoryUpdateAsync(string stype, string cateName, string catekeyword, string sid, string minscore) {
            this.CategoryUpdateAsync(stype, cateName, catekeyword, sid, minscore, null);
        }
        
        /// <remarks/>
        public void CategoryUpdateAsync(string stype, string cateName, string catekeyword, string sid, string minscore, object userState) {
            if ((this.CategoryUpdateOperationCompleted == null)) {
                this.CategoryUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCategoryUpdateOperationCompleted);
            }
            this.InvokeAsync("CategoryUpdate", new object[] {
                        stype,
                        cateName,
                        catekeyword,
                        sid,
                        minscore}, this.CategoryUpdateOperationCompleted, userState);
        }
        
        private void OnCategoryUpdateOperationCompleted(object arg) {
            if ((this.CategoryUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CategoryUpdateCompleted(this, new CategoryUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DelCategory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DelCategory(string cateid) {
            object[] results = this.Invoke("DelCategory", new object[] {
                        cateid});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DelCategoryAsync(string cateid) {
            this.DelCategoryAsync(cateid, null);
        }
        
        /// <remarks/>
        public void DelCategoryAsync(string cateid, object userState) {
            if ((this.DelCategoryOperationCompleted == null)) {
                this.DelCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelCategoryOperationCompleted);
            }
            this.InvokeAsync("DelCategory", new object[] {
                        cateid}, this.DelCategoryOperationCompleted, userState);
        }
        
        private void OnDelCategoryOperationCompleted(object arg) {
            if ((this.DelCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DelCategoryCompleted(this, new DelCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InitKeywordsList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InitKeywordsList() {
            object[] results = this.Invoke("InitKeywordsList", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InitKeywordsListAsync() {
            this.InitKeywordsListAsync(null);
        }
        
        /// <remarks/>
        public void InitKeywordsListAsync(object userState) {
            if ((this.InitKeywordsListOperationCompleted == null)) {
                this.InitKeywordsListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitKeywordsListOperationCompleted);
            }
            this.InvokeAsync("InitKeywordsList", new object[0], this.InitKeywordsListOperationCompleted, userState);
        }
        
        private void OnInitKeywordsListOperationCompleted(object arg) {
            if ((this.InitKeywordsListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InitKeywordsListCompleted(this, new InitKeywordsListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DelKeywords", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DelKeywords(string kwid) {
            object[] results = this.Invoke("DelKeywords", new object[] {
                        kwid});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DelKeywordsAsync(string kwid) {
            this.DelKeywordsAsync(kwid, null);
        }
        
        /// <remarks/>
        public void DelKeywordsAsync(string kwid, object userState) {
            if ((this.DelKeywordsOperationCompleted == null)) {
                this.DelKeywordsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelKeywordsOperationCompleted);
            }
            this.InvokeAsync("DelKeywords", new object[] {
                        kwid}, this.DelKeywordsOperationCompleted, userState);
        }
        
        private void OnDelKeywordsOperationCompleted(object arg) {
            if ((this.DelKeywordsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DelKeywordsCompleted(this, new DelKeywordsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KeywordsUpdate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool KeywordsUpdate(string kwstype, string kwcateName, string kwRelevance, string kwsid) {
            object[] results = this.Invoke("KeywordsUpdate", new object[] {
                        kwstype,
                        kwcateName,
                        kwRelevance,
                        kwsid});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void KeywordsUpdateAsync(string kwstype, string kwcateName, string kwRelevance, string kwsid) {
            this.KeywordsUpdateAsync(kwstype, kwcateName, kwRelevance, kwsid, null);
        }
        
        /// <remarks/>
        public void KeywordsUpdateAsync(string kwstype, string kwcateName, string kwRelevance, string kwsid, object userState) {
            if ((this.KeywordsUpdateOperationCompleted == null)) {
                this.KeywordsUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKeywordsUpdateOperationCompleted);
            }
            this.InvokeAsync("KeywordsUpdate", new object[] {
                        kwstype,
                        kwcateName,
                        kwRelevance,
                        kwsid}, this.KeywordsUpdateOperationCompleted, userState);
        }
        
        private void OnKeywordsUpdateOperationCompleted(object arg) {
            if ((this.KeywordsUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KeywordsUpdateCompleted(this, new KeywordsUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserGroupList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserGroupList(string attentiontype, string mainUid) {
            object[] results = this.Invoke("GetUserGroupList", new object[] {
                        attentiontype,
                        mainUid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserGroupListAsync(string attentiontype, string mainUid) {
            this.GetUserGroupListAsync(attentiontype, mainUid, null);
        }
        
        /// <remarks/>
        public void GetUserGroupListAsync(string attentiontype, string mainUid, object userState) {
            if ((this.GetUserGroupListOperationCompleted == null)) {
                this.GetUserGroupListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserGroupListOperationCompleted);
            }
            this.InvokeAsync("GetUserGroupList", new object[] {
                        attentiontype,
                        mainUid}, this.GetUserGroupListOperationCompleted, userState);
        }
        
        private void OnGetUserGroupListOperationCompleted(object arg) {
            if ((this.GetUserGroupListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserGroupListCompleted(this, new GetUserGroupListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GroupToAttention", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GroupToAttention(string groupid, string grids) {
            object[] results = this.Invoke("GroupToAttention", new object[] {
                        groupid,
                        grids});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GroupToAttentionAsync(string groupid, string grids) {
            this.GroupToAttentionAsync(groupid, grids, null);
        }
        
        /// <remarks/>
        public void GroupToAttentionAsync(string groupid, string grids, object userState) {
            if ((this.GroupToAttentionOperationCompleted == null)) {
                this.GroupToAttentionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGroupToAttentionOperationCompleted);
            }
            this.InvokeAsync("GroupToAttention", new object[] {
                        groupid,
                        grids}, this.GroupToAttentionOperationCompleted, userState);
        }
        
        private void OnGroupToAttentionOperationCompleted(object arg) {
            if ((this.GroupToAttentionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GroupToAttentionCompleted(this, new GroupToAttentionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GroupAttentionUpdate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GroupAttentionUpdate(string updategroupid, string updategrouptxt) {
            object[] results = this.Invoke("GroupAttentionUpdate", new object[] {
                        updategroupid,
                        updategrouptxt});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GroupAttentionUpdateAsync(string updategroupid, string updategrouptxt) {
            this.GroupAttentionUpdateAsync(updategroupid, updategrouptxt, null);
        }
        
        /// <remarks/>
        public void GroupAttentionUpdateAsync(string updategroupid, string updategrouptxt, object userState) {
            if ((this.GroupAttentionUpdateOperationCompleted == null)) {
                this.GroupAttentionUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGroupAttentionUpdateOperationCompleted);
            }
            this.InvokeAsync("GroupAttentionUpdate", new object[] {
                        updategroupid,
                        updategrouptxt}, this.GroupAttentionUpdateOperationCompleted, userState);
        }
        
        private void OnGroupAttentionUpdateOperationCompleted(object arg) {
            if ((this.GroupAttentionUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GroupAttentionUpdateCompleted(this, new GroupAttentionUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddGroupAttention", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddGroupAttention(string addgroupname, string addgroupAttentionType, string addgroupmainid) {
            object[] results = this.Invoke("AddGroupAttention", new object[] {
                        addgroupname,
                        addgroupAttentionType,
                        addgroupmainid});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddGroupAttentionAsync(string addgroupname, string addgroupAttentionType, string addgroupmainid) {
            this.AddGroupAttentionAsync(addgroupname, addgroupAttentionType, addgroupmainid, null);
        }
        
        /// <remarks/>
        public void AddGroupAttentionAsync(string addgroupname, string addgroupAttentionType, string addgroupmainid, object userState) {
            if ((this.AddGroupAttentionOperationCompleted == null)) {
                this.AddGroupAttentionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddGroupAttentionOperationCompleted);
            }
            this.InvokeAsync("AddGroupAttention", new object[] {
                        addgroupname,
                        addgroupAttentionType,
                        addgroupmainid}, this.AddGroupAttentionOperationCompleted, userState);
        }
        
        private void OnAddGroupAttentionOperationCompleted(object arg) {
            if ((this.AddGroupAttentionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddGroupAttentionCompleted(this, new AddGroupAttentionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DelAttentionGroup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DelAttentionGroup(string atgId) {
            object[] results = this.Invoke("DelAttentionGroup", new object[] {
                        atgId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DelAttentionGroupAsync(string atgId) {
            this.DelAttentionGroupAsync(atgId, null);
        }
        
        /// <remarks/>
        public void DelAttentionGroupAsync(string atgId, object userState) {
            if ((this.DelAttentionGroupOperationCompleted == null)) {
                this.DelAttentionGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelAttentionGroupOperationCompleted);
            }
            this.InvokeAsync("DelAttentionGroup", new object[] {
                        atgId}, this.DelAttentionGroupOperationCompleted, userState);
        }
        
        private void OnDelAttentionGroupOperationCompleted(object arg) {
            if ((this.DelAttentionGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DelAttentionGroupCompleted(this, new DelAttentionGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StatisticTopic", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string StatisticTopic(string topicid) {
            object[] results = this.Invoke("StatisticTopic", new object[] {
                        topicid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StatisticTopicAsync(string topicid) {
            this.StatisticTopicAsync(topicid, null);
        }
        
        /// <remarks/>
        public void StatisticTopicAsync(string topicid, object userState) {
            if ((this.StatisticTopicOperationCompleted == null)) {
                this.StatisticTopicOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStatisticTopicOperationCompleted);
            }
            this.InvokeAsync("StatisticTopic", new object[] {
                        topicid}, this.StatisticTopicOperationCompleted, userState);
        }
        
        private void OnStatisticTopicOperationCompleted(object arg) {
            if ((this.StatisticTopicCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StatisticTopicCompleted(this, new StatisticTopicCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetTopicPagerCompletedEventHandler(object sender, GetTopicPagerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTopicPagerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTopicPagerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetUserPagerCompletedEventHandler(object sender, GetUserPagerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserPagerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserPagerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void TopicUpdateCompletedEventHandler(object sender, TopicUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TopicUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TopicUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetHotTopicCompletedEventHandler(object sender, GetHotTopicCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHotTopicCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHotTopicCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void InitCategoryCompletedEventHandler(object sender, InitCategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InitCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InitCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void CategoryUpdateCompletedEventHandler(object sender, CategoryUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CategoryUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CategoryUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void DelCategoryCompletedEventHandler(object sender, DelCategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DelCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DelCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void InitKeywordsListCompletedEventHandler(object sender, InitKeywordsListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InitKeywordsListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InitKeywordsListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void DelKeywordsCompletedEventHandler(object sender, DelKeywordsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DelKeywordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DelKeywordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void KeywordsUpdateCompletedEventHandler(object sender, KeywordsUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KeywordsUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KeywordsUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetUserGroupListCompletedEventHandler(object sender, GetUserGroupListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserGroupListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserGroupListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GroupToAttentionCompletedEventHandler(object sender, GroupToAttentionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GroupToAttentionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GroupToAttentionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GroupAttentionUpdateCompletedEventHandler(object sender, GroupAttentionUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GroupAttentionUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GroupAttentionUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void AddGroupAttentionCompletedEventHandler(object sender, AddGroupAttentionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddGroupAttentionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddGroupAttentionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void DelAttentionGroupCompletedEventHandler(object sender, DelAttentionGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DelAttentionGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DelAttentionGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void StatisticTopicCompletedEventHandler(object sender, StatisticTopicCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StatisticTopicCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StatisticTopicCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591