//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5456
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeiboAnalysis.WeiboDataSource {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WeiboDataSource.WeiboDataServiceSoap")]
    public interface WeiboDataServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 keywords 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTopicPager", ReplyAction="*")]
        WeiboAnalysis.WeiboDataSource.GetTopicPagerResponse GetTopicPager(WeiboAnalysis.WeiboDataSource.GetTopicPagerRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 groupId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserPager", ReplyAction="*")]
        WeiboAnalysis.WeiboDataSource.GetUserPagerResponse GetUserPager(WeiboAnalysis.WeiboDataSource.GetUserPagerRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 tname 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TopicUpdate", ReplyAction="*")]
        WeiboAnalysis.WeiboDataSource.TopicUpdateResponse TopicUpdate(WeiboAnalysis.WeiboDataSource.TopicUpdateRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 topicType 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHotTopic", ReplyAction="*")]
        WeiboAnalysis.WeiboDataSource.GetHotTopicResponse GetHotTopic(WeiboAnalysis.WeiboDataSource.GetHotTopicRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 InitCategoryResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InitCategory", ReplyAction="*")]
        WeiboAnalysis.WeiboDataSource.InitCategoryResponse InitCategory(WeiboAnalysis.WeiboDataSource.InitCategoryRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 stype 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CategoryUpdate", ReplyAction="*")]
        WeiboAnalysis.WeiboDataSource.CategoryUpdateResponse CategoryUpdate(WeiboAnalysis.WeiboDataSource.CategoryUpdateRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 cateid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelCategory", ReplyAction="*")]
        WeiboAnalysis.WeiboDataSource.DelCategoryResponse DelCategory(WeiboAnalysis.WeiboDataSource.DelCategoryRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 InitKeywordsListResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InitKeywordsList", ReplyAction="*")]
        WeiboAnalysis.WeiboDataSource.InitKeywordsListResponse InitKeywordsList(WeiboAnalysis.WeiboDataSource.InitKeywordsListRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 kwid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelKeywords", ReplyAction="*")]
        WeiboAnalysis.WeiboDataSource.DelKeywordsResponse DelKeywords(WeiboAnalysis.WeiboDataSource.DelKeywordsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 kwstype 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KeywordsUpdate", ReplyAction="*")]
        WeiboAnalysis.WeiboDataSource.KeywordsUpdateResponse KeywordsUpdate(WeiboAnalysis.WeiboDataSource.KeywordsUpdateRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 attentiontype 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserGroupList", ReplyAction="*")]
        WeiboAnalysis.WeiboDataSource.GetUserGroupListResponse GetUserGroupList(WeiboAnalysis.WeiboDataSource.GetUserGroupListRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 groupid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GroupToAttention", ReplyAction="*")]
        WeiboAnalysis.WeiboDataSource.GroupToAttentionResponse GroupToAttention(WeiboAnalysis.WeiboDataSource.GroupToAttentionRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 updategroupid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GroupAttentionUpdate", ReplyAction="*")]
        WeiboAnalysis.WeiboDataSource.GroupAttentionUpdateResponse GroupAttentionUpdate(WeiboAnalysis.WeiboDataSource.GroupAttentionUpdateRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 addgroupname 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddGroupAttention", ReplyAction="*")]
        WeiboAnalysis.WeiboDataSource.AddGroupAttentionResponse AddGroupAttention(WeiboAnalysis.WeiboDataSource.AddGroupAttentionRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 atgId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelAttentionGroup", ReplyAction="*")]
        WeiboAnalysis.WeiboDataSource.DelAttentionGroupResponse DelAttentionGroup(WeiboAnalysis.WeiboDataSource.DelAttentionGroupRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 topicid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StatisticTopic", ReplyAction="*")]
        WeiboAnalysis.WeiboDataSource.StatisticTopicResponse StatisticTopic(WeiboAnalysis.WeiboDataSource.StatisticTopicRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTopicPagerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTopicPager", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.GetTopicPagerRequestBody Body;
        
        public GetTopicPagerRequest() {
        }
        
        public GetTopicPagerRequest(WeiboAnalysis.WeiboDataSource.GetTopicPagerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTopicPagerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string keywords;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string topicindustry;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string stime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string etime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int start;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int pagesize;
        
        public GetTopicPagerRequestBody() {
        }
        
        public GetTopicPagerRequestBody(string keywords, string topicindustry, string stime, string etime, int start, int pagesize) {
            this.keywords = keywords;
            this.topicindustry = topicindustry;
            this.stime = stime;
            this.etime = etime;
            this.start = start;
            this.pagesize = pagesize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTopicPagerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTopicPagerResponse", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.GetTopicPagerResponseBody Body;
        
        public GetTopicPagerResponse() {
        }
        
        public GetTopicPagerResponse(WeiboAnalysis.WeiboDataSource.GetTopicPagerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTopicPagerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTopicPagerResult;
        
        public GetTopicPagerResponseBody() {
        }
        
        public GetTopicPagerResponseBody(string GetTopicPagerResult) {
            this.GetTopicPagerResult = GetTopicPagerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserPagerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserPager", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.GetUserPagerRequestBody Body;
        
        public GetUserPagerRequest() {
        }
        
        public GetUserPagerRequest(WeiboAnalysis.WeiboDataSource.GetUserPagerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserPagerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string groupId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mainuid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string websource;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string attentionType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int start;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int pagesize;
        
        public GetUserPagerRequestBody() {
        }
        
        public GetUserPagerRequestBody(string groupId, string mainuid, string websource, string attentionType, int start, int pagesize) {
            this.groupId = groupId;
            this.mainuid = mainuid;
            this.websource = websource;
            this.attentionType = attentionType;
            this.start = start;
            this.pagesize = pagesize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserPagerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserPagerResponse", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.GetUserPagerResponseBody Body;
        
        public GetUserPagerResponse() {
        }
        
        public GetUserPagerResponse(WeiboAnalysis.WeiboDataSource.GetUserPagerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserPagerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserPagerResult;
        
        public GetUserPagerResponseBody() {
        }
        
        public GetUserPagerResponseBody(string GetUserPagerResult) {
            this.GetUserPagerResult = GetUserPagerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TopicUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TopicUpdate", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.TopicUpdateRequestBody Body;
        
        public TopicUpdateRequest() {
        }
        
        public TopicUpdateRequest(WeiboAnalysis.WeiboDataSource.TopicUpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TopicUpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string keyword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string industry;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string stype;
        
        public TopicUpdateRequestBody() {
        }
        
        public TopicUpdateRequestBody(string tname, string keyword, string industry, string sid, string stype) {
            this.tname = tname;
            this.keyword = keyword;
            this.industry = industry;
            this.sid = sid;
            this.stype = stype;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TopicUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TopicUpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.TopicUpdateResponseBody Body;
        
        public TopicUpdateResponse() {
        }
        
        public TopicUpdateResponse(WeiboAnalysis.WeiboDataSource.TopicUpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TopicUpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool TopicUpdateResult;
        
        public TopicUpdateResponseBody() {
        }
        
        public TopicUpdateResponseBody(bool TopicUpdateResult) {
            this.TopicUpdateResult = TopicUpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHotTopicRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHotTopic", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.GetHotTopicRequestBody Body;
        
        public GetHotTopicRequest() {
        }
        
        public GetHotTopicRequest(WeiboAnalysis.WeiboDataSource.GetHotTopicRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHotTopicRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string topicType;
        
        public GetHotTopicRequestBody() {
        }
        
        public GetHotTopicRequestBody(string topicType) {
            this.topicType = topicType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHotTopicResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHotTopicResponse", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.GetHotTopicResponseBody Body;
        
        public GetHotTopicResponse() {
        }
        
        public GetHotTopicResponse(WeiboAnalysis.WeiboDataSource.GetHotTopicResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHotTopicResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetHotTopicResult;
        
        public GetHotTopicResponseBody() {
        }
        
        public GetHotTopicResponseBody(string GetHotTopicResult) {
            this.GetHotTopicResult = GetHotTopicResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InitCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InitCategory", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.InitCategoryRequestBody Body;
        
        public InitCategoryRequest() {
        }
        
        public InitCategoryRequest(WeiboAnalysis.WeiboDataSource.InitCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InitCategoryRequestBody {
        
        public InitCategoryRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InitCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InitCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.InitCategoryResponseBody Body;
        
        public InitCategoryResponse() {
        }
        
        public InitCategoryResponse(WeiboAnalysis.WeiboDataSource.InitCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InitCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InitCategoryResult;
        
        public InitCategoryResponseBody() {
        }
        
        public InitCategoryResponseBody(string InitCategoryResult) {
            this.InitCategoryResult = InitCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CategoryUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CategoryUpdate", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.CategoryUpdateRequestBody Body;
        
        public CategoryUpdateRequest() {
        }
        
        public CategoryUpdateRequest(WeiboAnalysis.WeiboDataSource.CategoryUpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CategoryUpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string stype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cateName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string catekeyword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string minscore;
        
        public CategoryUpdateRequestBody() {
        }
        
        public CategoryUpdateRequestBody(string stype, string cateName, string catekeyword, string sid, string minscore) {
            this.stype = stype;
            this.cateName = cateName;
            this.catekeyword = catekeyword;
            this.sid = sid;
            this.minscore = minscore;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CategoryUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CategoryUpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.CategoryUpdateResponseBody Body;
        
        public CategoryUpdateResponse() {
        }
        
        public CategoryUpdateResponse(WeiboAnalysis.WeiboDataSource.CategoryUpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CategoryUpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CategoryUpdateResult;
        
        public CategoryUpdateResponseBody() {
        }
        
        public CategoryUpdateResponseBody(bool CategoryUpdateResult) {
            this.CategoryUpdateResult = CategoryUpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelCategory", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.DelCategoryRequestBody Body;
        
        public DelCategoryRequest() {
        }
        
        public DelCategoryRequest(WeiboAnalysis.WeiboDataSource.DelCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cateid;
        
        public DelCategoryRequestBody() {
        }
        
        public DelCategoryRequestBody(string cateid) {
            this.cateid = cateid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.DelCategoryResponseBody Body;
        
        public DelCategoryResponse() {
        }
        
        public DelCategoryResponse(WeiboAnalysis.WeiboDataSource.DelCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DelCategoryResult;
        
        public DelCategoryResponseBody() {
        }
        
        public DelCategoryResponseBody(bool DelCategoryResult) {
            this.DelCategoryResult = DelCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InitKeywordsListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InitKeywordsList", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.InitKeywordsListRequestBody Body;
        
        public InitKeywordsListRequest() {
        }
        
        public InitKeywordsListRequest(WeiboAnalysis.WeiboDataSource.InitKeywordsListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InitKeywordsListRequestBody {
        
        public InitKeywordsListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InitKeywordsListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InitKeywordsListResponse", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.InitKeywordsListResponseBody Body;
        
        public InitKeywordsListResponse() {
        }
        
        public InitKeywordsListResponse(WeiboAnalysis.WeiboDataSource.InitKeywordsListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InitKeywordsListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InitKeywordsListResult;
        
        public InitKeywordsListResponseBody() {
        }
        
        public InitKeywordsListResponseBody(string InitKeywordsListResult) {
            this.InitKeywordsListResult = InitKeywordsListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelKeywordsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelKeywords", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.DelKeywordsRequestBody Body;
        
        public DelKeywordsRequest() {
        }
        
        public DelKeywordsRequest(WeiboAnalysis.WeiboDataSource.DelKeywordsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelKeywordsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string kwid;
        
        public DelKeywordsRequestBody() {
        }
        
        public DelKeywordsRequestBody(string kwid) {
            this.kwid = kwid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelKeywordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelKeywordsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.DelKeywordsResponseBody Body;
        
        public DelKeywordsResponse() {
        }
        
        public DelKeywordsResponse(WeiboAnalysis.WeiboDataSource.DelKeywordsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelKeywordsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DelKeywordsResult;
        
        public DelKeywordsResponseBody() {
        }
        
        public DelKeywordsResponseBody(bool DelKeywordsResult) {
            this.DelKeywordsResult = DelKeywordsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KeywordsUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KeywordsUpdate", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.KeywordsUpdateRequestBody Body;
        
        public KeywordsUpdateRequest() {
        }
        
        public KeywordsUpdateRequest(WeiboAnalysis.WeiboDataSource.KeywordsUpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KeywordsUpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string kwstype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string kwcateName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string kwRelevance;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string kwsid;
        
        public KeywordsUpdateRequestBody() {
        }
        
        public KeywordsUpdateRequestBody(string kwstype, string kwcateName, string kwRelevance, string kwsid) {
            this.kwstype = kwstype;
            this.kwcateName = kwcateName;
            this.kwRelevance = kwRelevance;
            this.kwsid = kwsid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KeywordsUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KeywordsUpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.KeywordsUpdateResponseBody Body;
        
        public KeywordsUpdateResponse() {
        }
        
        public KeywordsUpdateResponse(WeiboAnalysis.WeiboDataSource.KeywordsUpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KeywordsUpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool KeywordsUpdateResult;
        
        public KeywordsUpdateResponseBody() {
        }
        
        public KeywordsUpdateResponseBody(bool KeywordsUpdateResult) {
            this.KeywordsUpdateResult = KeywordsUpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserGroupListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserGroupList", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.GetUserGroupListRequestBody Body;
        
        public GetUserGroupListRequest() {
        }
        
        public GetUserGroupListRequest(WeiboAnalysis.WeiboDataSource.GetUserGroupListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserGroupListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string attentiontype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mainUid;
        
        public GetUserGroupListRequestBody() {
        }
        
        public GetUserGroupListRequestBody(string attentiontype, string mainUid) {
            this.attentiontype = attentiontype;
            this.mainUid = mainUid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserGroupListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserGroupListResponse", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.GetUserGroupListResponseBody Body;
        
        public GetUserGroupListResponse() {
        }
        
        public GetUserGroupListResponse(WeiboAnalysis.WeiboDataSource.GetUserGroupListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserGroupListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserGroupListResult;
        
        public GetUserGroupListResponseBody() {
        }
        
        public GetUserGroupListResponseBody(string GetUserGroupListResult) {
            this.GetUserGroupListResult = GetUserGroupListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GroupToAttentionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GroupToAttention", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.GroupToAttentionRequestBody Body;
        
        public GroupToAttentionRequest() {
        }
        
        public GroupToAttentionRequest(WeiboAnalysis.WeiboDataSource.GroupToAttentionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GroupToAttentionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string groupid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string grids;
        
        public GroupToAttentionRequestBody() {
        }
        
        public GroupToAttentionRequestBody(string groupid, string grids) {
            this.groupid = groupid;
            this.grids = grids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GroupToAttentionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GroupToAttentionResponse", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.GroupToAttentionResponseBody Body;
        
        public GroupToAttentionResponse() {
        }
        
        public GroupToAttentionResponse(WeiboAnalysis.WeiboDataSource.GroupToAttentionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GroupToAttentionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GroupToAttentionResult;
        
        public GroupToAttentionResponseBody() {
        }
        
        public GroupToAttentionResponseBody(bool GroupToAttentionResult) {
            this.GroupToAttentionResult = GroupToAttentionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GroupAttentionUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GroupAttentionUpdate", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.GroupAttentionUpdateRequestBody Body;
        
        public GroupAttentionUpdateRequest() {
        }
        
        public GroupAttentionUpdateRequest(WeiboAnalysis.WeiboDataSource.GroupAttentionUpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GroupAttentionUpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string updategroupid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string updategrouptxt;
        
        public GroupAttentionUpdateRequestBody() {
        }
        
        public GroupAttentionUpdateRequestBody(string updategroupid, string updategrouptxt) {
            this.updategroupid = updategroupid;
            this.updategrouptxt = updategrouptxt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GroupAttentionUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GroupAttentionUpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.GroupAttentionUpdateResponseBody Body;
        
        public GroupAttentionUpdateResponse() {
        }
        
        public GroupAttentionUpdateResponse(WeiboAnalysis.WeiboDataSource.GroupAttentionUpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GroupAttentionUpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GroupAttentionUpdateResult;
        
        public GroupAttentionUpdateResponseBody() {
        }
        
        public GroupAttentionUpdateResponseBody(bool GroupAttentionUpdateResult) {
            this.GroupAttentionUpdateResult = GroupAttentionUpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddGroupAttentionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddGroupAttention", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.AddGroupAttentionRequestBody Body;
        
        public AddGroupAttentionRequest() {
        }
        
        public AddGroupAttentionRequest(WeiboAnalysis.WeiboDataSource.AddGroupAttentionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddGroupAttentionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addgroupname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string addgroupAttentionType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string addgroupmainid;
        
        public AddGroupAttentionRequestBody() {
        }
        
        public AddGroupAttentionRequestBody(string addgroupname, string addgroupAttentionType, string addgroupmainid) {
            this.addgroupname = addgroupname;
            this.addgroupAttentionType = addgroupAttentionType;
            this.addgroupmainid = addgroupmainid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddGroupAttentionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddGroupAttentionResponse", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.AddGroupAttentionResponseBody Body;
        
        public AddGroupAttentionResponse() {
        }
        
        public AddGroupAttentionResponse(WeiboAnalysis.WeiboDataSource.AddGroupAttentionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddGroupAttentionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddGroupAttentionResult;
        
        public AddGroupAttentionResponseBody() {
        }
        
        public AddGroupAttentionResponseBody(int AddGroupAttentionResult) {
            this.AddGroupAttentionResult = AddGroupAttentionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelAttentionGroupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelAttentionGroup", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.DelAttentionGroupRequestBody Body;
        
        public DelAttentionGroupRequest() {
        }
        
        public DelAttentionGroupRequest(WeiboAnalysis.WeiboDataSource.DelAttentionGroupRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelAttentionGroupRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string atgId;
        
        public DelAttentionGroupRequestBody() {
        }
        
        public DelAttentionGroupRequestBody(string atgId) {
            this.atgId = atgId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelAttentionGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelAttentionGroupResponse", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.DelAttentionGroupResponseBody Body;
        
        public DelAttentionGroupResponse() {
        }
        
        public DelAttentionGroupResponse(WeiboAnalysis.WeiboDataSource.DelAttentionGroupResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelAttentionGroupResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DelAttentionGroupResult;
        
        public DelAttentionGroupResponseBody() {
        }
        
        public DelAttentionGroupResponseBody(bool DelAttentionGroupResult) {
            this.DelAttentionGroupResult = DelAttentionGroupResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatisticTopicRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StatisticTopic", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.StatisticTopicRequestBody Body;
        
        public StatisticTopicRequest() {
        }
        
        public StatisticTopicRequest(WeiboAnalysis.WeiboDataSource.StatisticTopicRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StatisticTopicRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string topicid;
        
        public StatisticTopicRequestBody() {
        }
        
        public StatisticTopicRequestBody(string topicid) {
            this.topicid = topicid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatisticTopicResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StatisticTopicResponse", Namespace="http://tempuri.org/", Order=0)]
        public WeiboAnalysis.WeiboDataSource.StatisticTopicResponseBody Body;
        
        public StatisticTopicResponse() {
        }
        
        public StatisticTopicResponse(WeiboAnalysis.WeiboDataSource.StatisticTopicResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StatisticTopicResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StatisticTopicResult;
        
        public StatisticTopicResponseBody() {
        }
        
        public StatisticTopicResponseBody(string StatisticTopicResult) {
            this.StatisticTopicResult = StatisticTopicResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface WeiboDataServiceSoapChannel : WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WeiboDataServiceSoapClient : System.ServiceModel.ClientBase<WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap>, WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap {
        
        public WeiboDataServiceSoapClient() {
        }
        
        public WeiboDataServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeiboDataServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeiboDataServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeiboDataServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeiboAnalysis.WeiboDataSource.GetTopicPagerResponse WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap.GetTopicPager(WeiboAnalysis.WeiboDataSource.GetTopicPagerRequest request) {
            return base.Channel.GetTopicPager(request);
        }
        
        public string GetTopicPager(string keywords, string topicindustry, string stime, string etime, int start, int pagesize) {
            WeiboAnalysis.WeiboDataSource.GetTopicPagerRequest inValue = new WeiboAnalysis.WeiboDataSource.GetTopicPagerRequest();
            inValue.Body = new WeiboAnalysis.WeiboDataSource.GetTopicPagerRequestBody();
            inValue.Body.keywords = keywords;
            inValue.Body.topicindustry = topicindustry;
            inValue.Body.stime = stime;
            inValue.Body.etime = etime;
            inValue.Body.start = start;
            inValue.Body.pagesize = pagesize;
            WeiboAnalysis.WeiboDataSource.GetTopicPagerResponse retVal = ((WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap)(this)).GetTopicPager(inValue);
            return retVal.Body.GetTopicPagerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeiboAnalysis.WeiboDataSource.GetUserPagerResponse WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap.GetUserPager(WeiboAnalysis.WeiboDataSource.GetUserPagerRequest request) {
            return base.Channel.GetUserPager(request);
        }
        
        public string GetUserPager(string groupId, string mainuid, string websource, string attentionType, int start, int pagesize) {
            WeiboAnalysis.WeiboDataSource.GetUserPagerRequest inValue = new WeiboAnalysis.WeiboDataSource.GetUserPagerRequest();
            inValue.Body = new WeiboAnalysis.WeiboDataSource.GetUserPagerRequestBody();
            inValue.Body.groupId = groupId;
            inValue.Body.mainuid = mainuid;
            inValue.Body.websource = websource;
            inValue.Body.attentionType = attentionType;
            inValue.Body.start = start;
            inValue.Body.pagesize = pagesize;
            WeiboAnalysis.WeiboDataSource.GetUserPagerResponse retVal = ((WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap)(this)).GetUserPager(inValue);
            return retVal.Body.GetUserPagerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeiboAnalysis.WeiboDataSource.TopicUpdateResponse WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap.TopicUpdate(WeiboAnalysis.WeiboDataSource.TopicUpdateRequest request) {
            return base.Channel.TopicUpdate(request);
        }
        
        public bool TopicUpdate(string tname, string keyword, string industry, string sid, string stype) {
            WeiboAnalysis.WeiboDataSource.TopicUpdateRequest inValue = new WeiboAnalysis.WeiboDataSource.TopicUpdateRequest();
            inValue.Body = new WeiboAnalysis.WeiboDataSource.TopicUpdateRequestBody();
            inValue.Body.tname = tname;
            inValue.Body.keyword = keyword;
            inValue.Body.industry = industry;
            inValue.Body.sid = sid;
            inValue.Body.stype = stype;
            WeiboAnalysis.WeiboDataSource.TopicUpdateResponse retVal = ((WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap)(this)).TopicUpdate(inValue);
            return retVal.Body.TopicUpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeiboAnalysis.WeiboDataSource.GetHotTopicResponse WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap.GetHotTopic(WeiboAnalysis.WeiboDataSource.GetHotTopicRequest request) {
            return base.Channel.GetHotTopic(request);
        }
        
        public string GetHotTopic(string topicType) {
            WeiboAnalysis.WeiboDataSource.GetHotTopicRequest inValue = new WeiboAnalysis.WeiboDataSource.GetHotTopicRequest();
            inValue.Body = new WeiboAnalysis.WeiboDataSource.GetHotTopicRequestBody();
            inValue.Body.topicType = topicType;
            WeiboAnalysis.WeiboDataSource.GetHotTopicResponse retVal = ((WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap)(this)).GetHotTopic(inValue);
            return retVal.Body.GetHotTopicResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeiboAnalysis.WeiboDataSource.InitCategoryResponse WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap.InitCategory(WeiboAnalysis.WeiboDataSource.InitCategoryRequest request) {
            return base.Channel.InitCategory(request);
        }
        
        public string InitCategory() {
            WeiboAnalysis.WeiboDataSource.InitCategoryRequest inValue = new WeiboAnalysis.WeiboDataSource.InitCategoryRequest();
            inValue.Body = new WeiboAnalysis.WeiboDataSource.InitCategoryRequestBody();
            WeiboAnalysis.WeiboDataSource.InitCategoryResponse retVal = ((WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap)(this)).InitCategory(inValue);
            return retVal.Body.InitCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeiboAnalysis.WeiboDataSource.CategoryUpdateResponse WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap.CategoryUpdate(WeiboAnalysis.WeiboDataSource.CategoryUpdateRequest request) {
            return base.Channel.CategoryUpdate(request);
        }
        
        public bool CategoryUpdate(string stype, string cateName, string catekeyword, string sid, string minscore) {
            WeiboAnalysis.WeiboDataSource.CategoryUpdateRequest inValue = new WeiboAnalysis.WeiboDataSource.CategoryUpdateRequest();
            inValue.Body = new WeiboAnalysis.WeiboDataSource.CategoryUpdateRequestBody();
            inValue.Body.stype = stype;
            inValue.Body.cateName = cateName;
            inValue.Body.catekeyword = catekeyword;
            inValue.Body.sid = sid;
            inValue.Body.minscore = minscore;
            WeiboAnalysis.WeiboDataSource.CategoryUpdateResponse retVal = ((WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap)(this)).CategoryUpdate(inValue);
            return retVal.Body.CategoryUpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeiboAnalysis.WeiboDataSource.DelCategoryResponse WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap.DelCategory(WeiboAnalysis.WeiboDataSource.DelCategoryRequest request) {
            return base.Channel.DelCategory(request);
        }
        
        public bool DelCategory(string cateid) {
            WeiboAnalysis.WeiboDataSource.DelCategoryRequest inValue = new WeiboAnalysis.WeiboDataSource.DelCategoryRequest();
            inValue.Body = new WeiboAnalysis.WeiboDataSource.DelCategoryRequestBody();
            inValue.Body.cateid = cateid;
            WeiboAnalysis.WeiboDataSource.DelCategoryResponse retVal = ((WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap)(this)).DelCategory(inValue);
            return retVal.Body.DelCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeiboAnalysis.WeiboDataSource.InitKeywordsListResponse WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap.InitKeywordsList(WeiboAnalysis.WeiboDataSource.InitKeywordsListRequest request) {
            return base.Channel.InitKeywordsList(request);
        }
        
        public string InitKeywordsList() {
            WeiboAnalysis.WeiboDataSource.InitKeywordsListRequest inValue = new WeiboAnalysis.WeiboDataSource.InitKeywordsListRequest();
            inValue.Body = new WeiboAnalysis.WeiboDataSource.InitKeywordsListRequestBody();
            WeiboAnalysis.WeiboDataSource.InitKeywordsListResponse retVal = ((WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap)(this)).InitKeywordsList(inValue);
            return retVal.Body.InitKeywordsListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeiboAnalysis.WeiboDataSource.DelKeywordsResponse WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap.DelKeywords(WeiboAnalysis.WeiboDataSource.DelKeywordsRequest request) {
            return base.Channel.DelKeywords(request);
        }
        
        public bool DelKeywords(string kwid) {
            WeiboAnalysis.WeiboDataSource.DelKeywordsRequest inValue = new WeiboAnalysis.WeiboDataSource.DelKeywordsRequest();
            inValue.Body = new WeiboAnalysis.WeiboDataSource.DelKeywordsRequestBody();
            inValue.Body.kwid = kwid;
            WeiboAnalysis.WeiboDataSource.DelKeywordsResponse retVal = ((WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap)(this)).DelKeywords(inValue);
            return retVal.Body.DelKeywordsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeiboAnalysis.WeiboDataSource.KeywordsUpdateResponse WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap.KeywordsUpdate(WeiboAnalysis.WeiboDataSource.KeywordsUpdateRequest request) {
            return base.Channel.KeywordsUpdate(request);
        }
        
        public bool KeywordsUpdate(string kwstype, string kwcateName, string kwRelevance, string kwsid) {
            WeiboAnalysis.WeiboDataSource.KeywordsUpdateRequest inValue = new WeiboAnalysis.WeiboDataSource.KeywordsUpdateRequest();
            inValue.Body = new WeiboAnalysis.WeiboDataSource.KeywordsUpdateRequestBody();
            inValue.Body.kwstype = kwstype;
            inValue.Body.kwcateName = kwcateName;
            inValue.Body.kwRelevance = kwRelevance;
            inValue.Body.kwsid = kwsid;
            WeiboAnalysis.WeiboDataSource.KeywordsUpdateResponse retVal = ((WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap)(this)).KeywordsUpdate(inValue);
            return retVal.Body.KeywordsUpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeiboAnalysis.WeiboDataSource.GetUserGroupListResponse WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap.GetUserGroupList(WeiboAnalysis.WeiboDataSource.GetUserGroupListRequest request) {
            return base.Channel.GetUserGroupList(request);
        }
        
        public string GetUserGroupList(string attentiontype, string mainUid) {
            WeiboAnalysis.WeiboDataSource.GetUserGroupListRequest inValue = new WeiboAnalysis.WeiboDataSource.GetUserGroupListRequest();
            inValue.Body = new WeiboAnalysis.WeiboDataSource.GetUserGroupListRequestBody();
            inValue.Body.attentiontype = attentiontype;
            inValue.Body.mainUid = mainUid;
            WeiboAnalysis.WeiboDataSource.GetUserGroupListResponse retVal = ((WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap)(this)).GetUserGroupList(inValue);
            return retVal.Body.GetUserGroupListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeiboAnalysis.WeiboDataSource.GroupToAttentionResponse WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap.GroupToAttention(WeiboAnalysis.WeiboDataSource.GroupToAttentionRequest request) {
            return base.Channel.GroupToAttention(request);
        }
        
        public bool GroupToAttention(string groupid, string grids) {
            WeiboAnalysis.WeiboDataSource.GroupToAttentionRequest inValue = new WeiboAnalysis.WeiboDataSource.GroupToAttentionRequest();
            inValue.Body = new WeiboAnalysis.WeiboDataSource.GroupToAttentionRequestBody();
            inValue.Body.groupid = groupid;
            inValue.Body.grids = grids;
            WeiboAnalysis.WeiboDataSource.GroupToAttentionResponse retVal = ((WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap)(this)).GroupToAttention(inValue);
            return retVal.Body.GroupToAttentionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeiboAnalysis.WeiboDataSource.GroupAttentionUpdateResponse WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap.GroupAttentionUpdate(WeiboAnalysis.WeiboDataSource.GroupAttentionUpdateRequest request) {
            return base.Channel.GroupAttentionUpdate(request);
        }
        
        public bool GroupAttentionUpdate(string updategroupid, string updategrouptxt) {
            WeiboAnalysis.WeiboDataSource.GroupAttentionUpdateRequest inValue = new WeiboAnalysis.WeiboDataSource.GroupAttentionUpdateRequest();
            inValue.Body = new WeiboAnalysis.WeiboDataSource.GroupAttentionUpdateRequestBody();
            inValue.Body.updategroupid = updategroupid;
            inValue.Body.updategrouptxt = updategrouptxt;
            WeiboAnalysis.WeiboDataSource.GroupAttentionUpdateResponse retVal = ((WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap)(this)).GroupAttentionUpdate(inValue);
            return retVal.Body.GroupAttentionUpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeiboAnalysis.WeiboDataSource.AddGroupAttentionResponse WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap.AddGroupAttention(WeiboAnalysis.WeiboDataSource.AddGroupAttentionRequest request) {
            return base.Channel.AddGroupAttention(request);
        }
        
        public int AddGroupAttention(string addgroupname, string addgroupAttentionType, string addgroupmainid) {
            WeiboAnalysis.WeiboDataSource.AddGroupAttentionRequest inValue = new WeiboAnalysis.WeiboDataSource.AddGroupAttentionRequest();
            inValue.Body = new WeiboAnalysis.WeiboDataSource.AddGroupAttentionRequestBody();
            inValue.Body.addgroupname = addgroupname;
            inValue.Body.addgroupAttentionType = addgroupAttentionType;
            inValue.Body.addgroupmainid = addgroupmainid;
            WeiboAnalysis.WeiboDataSource.AddGroupAttentionResponse retVal = ((WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap)(this)).AddGroupAttention(inValue);
            return retVal.Body.AddGroupAttentionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeiboAnalysis.WeiboDataSource.DelAttentionGroupResponse WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap.DelAttentionGroup(WeiboAnalysis.WeiboDataSource.DelAttentionGroupRequest request) {
            return base.Channel.DelAttentionGroup(request);
        }
        
        public bool DelAttentionGroup(string atgId) {
            WeiboAnalysis.WeiboDataSource.DelAttentionGroupRequest inValue = new WeiboAnalysis.WeiboDataSource.DelAttentionGroupRequest();
            inValue.Body = new WeiboAnalysis.WeiboDataSource.DelAttentionGroupRequestBody();
            inValue.Body.atgId = atgId;
            WeiboAnalysis.WeiboDataSource.DelAttentionGroupResponse retVal = ((WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap)(this)).DelAttentionGroup(inValue);
            return retVal.Body.DelAttentionGroupResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeiboAnalysis.WeiboDataSource.StatisticTopicResponse WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap.StatisticTopic(WeiboAnalysis.WeiboDataSource.StatisticTopicRequest request) {
            return base.Channel.StatisticTopic(request);
        }
        
        public string StatisticTopic(string topicid) {
            WeiboAnalysis.WeiboDataSource.StatisticTopicRequest inValue = new WeiboAnalysis.WeiboDataSource.StatisticTopicRequest();
            inValue.Body = new WeiboAnalysis.WeiboDataSource.StatisticTopicRequestBody();
            inValue.Body.topicid = topicid;
            WeiboAnalysis.WeiboDataSource.StatisticTopicResponse retVal = ((WeiboAnalysis.WeiboDataSource.WeiboDataServiceSoap)(this)).StatisticTopic(inValue);
            return retVal.Body.StatisticTopicResult;
        }
    }
}
